"""Initial migration fixed

Revision ID: 15c8c906feb2
Revises: 
Create Date: 2025-12-01 16:53:17.929867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15c8c906feb2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zabytkowe_samochody',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marka_model', sa.String(length=255), nullable=True),
    sa.Column('rok_produkcji', sa.Integer(), nullable=True),
    sa.Column('czy_na_chodzie', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zabytkowe_samochody_id'), 'zabytkowe_samochody', ['id'], unique=False)
    op.create_index(op.f('ix_zabytkowe_samochody_marka_model'), 'zabytkowe_samochody', ['marka_model'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zabytkowe_samochody_marka_model'), table_name='zabytkowe_samochody')
    op.drop_index(op.f('ix_zabytkowe_samochody_id'), table_name='zabytkowe_samochody')
    op.drop_table('zabytkowe_samochody')
    # ### end Alembic commands ###
